version: '3'
services:
    db:
        build: ./mysql
        #image: mysql
        ports:
            - "3306:3306"
        volumes:
            - /Users/gary/docker/docker-eelly/data/mysql-data:/var/lib/mysql
        #new PDO("mysql:host=db;dbname=oauth;charset=utf8","root","123456");
        networks:
            app-network:
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            app-network:
    php5:
        build: ./php5-fpm
        volumes:
            - /Users/gary/site:/data/www
            - /Users/gary/docker/docker-eelly/logs:/data/logs
        links:
            - db
        networks:
            app-network:
    php7:
        build: ./php7-fpm
        volumes:
            - /Users/gary/site:/data/www
            - /Users/gary/docker/docker-eelly/logs:/data/logs
            - /Users/gary/docker/docker-eelly/html:/data/www/html
        links:
            - db
        networks:
            app-network:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php5
            - php7
        volumes:
            - /Users/gary/site:/data/www
            - /Users/gary/docker/docker-eelly/logs:/data/logs
            - /Users/gary/docker/docker-eelly/html:/data/www/html
        networks:
            app-network:
                aliases:
                    - api.eelly.dev
                    - www.eelly.dev
                    - m.eelly.dev
                    - static.eelly.dev
                    - manage.eelly.dev
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            app-network:
    redisCommander:
        image: tenstartups/redis-commander
        command: --redis-host redis
        links:
          - redis:redis
        ports:
          - "8081:8081"
        networks:
            app-network:
    memcached:
        image: memcached:latest
        expose:
            - 11211
        ports:
            - "11211:11211"
        networks:
            app-network:
    mongodb:
        image: 'tutum/mongodb'
        ports:
            - "27017:27017"
        environment:
            - AUTH=no
        #$manager = new MongoDB\Driver\Manager("mongodb://mongodb:27017");
        networks:
            app-network:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - "15672:15672"
            #http://api.eelly.dev:15672/#/
        networks:
            app-network:
    node:
        build: ./nodejs
        volumes:
             - /Users/gary/docker/docker-eelly/html:/data/www/html
             - /Users/gary/site:/data/www
        networks:
            app-network:
networks:
    app-network: